#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <string.h>
#include <sys/wait.h>
#include <unistd.h>
#include <time.h>
#include "prime.h"

// Size of each message.
#define MSGSIZE 20

int main(int argc, char *argv[]){
    
    // Array for pipe read/write.
    int fd[2];
    
    // Starting number.
    int number = 1;
    
    // New seed for rand().
    srand(time(NULL));

    // How many numbers to be generated by n and delta.
    int how_many = atoi(argv[1]);

    int delta = 1 + rand()%100;
    printf("Delta = %d\n\n", delta);

    // Returns 0 if created, -1 if not.
    int p = pipe(fd);
    
    if (p < 0){
        fprintf(stderr, "Pipe Failed.");
        exit(1);
    }

    // Returns 0+ if created, -1 if not.
    int f = fork();
    if (f < 0){
        fprintf(stderr, "Fork Failed.");
        exit(1);
    }

    // Father process: fork > 0
    else if (f > 0){
        // Impede-se a leitura.
        close(fd[0]);
        char write_n[MSGSIZE];
        
        for (int i = 0; i < how_many; i++){
            number += delta;
            sprintf(write_n, "%d", number);
            write(fd[1], write_n, MSGSIZE);
        }

        write(fd[1], "0", MSGSIZE);
        close(fd[1]);
        exit(0);
    }

    // Child process: fork == 0
    else{
        // Impede-se a escrita.
        close(fd[1]);
        
        char read_n[MSGSIZE];
        read(fd[0], read_n, MSGSIZE);
        int out = atoi(read_n);

        while (out){
            printf("Is number %d prime?\n", out);

            if (prime(out)) printf("Yes.\n\n");
            else printf("No.\n\n");

            read(fd[0], read_n, MSGSIZE);
            out = atoi(read_n);
        }

        printf("SIGTERM\n\n");
        close(fd[0]);
        exit(0);
    }
    return 0;
}
