#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <string.h>
#include <sys/wait.h>
#include <unistd.h>
#include <time.h>

// Size of each message.
#define MSGSIZE 20

int main(int argc, char *argv[]){
    
    // Array for pipe read/write.
    int fd[2];
    
    // Starting number.
    int n = 1;
    
    // New seed for rand().
    srand(time(NULL));

    // How many numbers to be generated by n and delta.
    int how_many = atoi(argv[1]);

    int delta = 1 + rand()%100;
    printf("Delta = %d\n\n", delta);

    // Returns 0 if created, -1 if not.
    int p = pipe(fd);
    
    if (p < 0){
        fprintf(stderr, "Pipe Failed.");
        exit(1);
    }

    // Returns 0+ if created, -1 if not.
    int f = fork();
    if (f < 0){
        fprintf(stderr, "Fork Failed.");
        exit(1);
    }

    // Father process: fork > 0
    else if (f > 0){
        
        // Impede-se a leitura.
        close(fd[0]);
        char str_n[MSGSIZE];
        
        for (int i = 0; i < how_many; i++){
            n += delta;
            sprintf(str_n, "%d", n);
            write(fd[1], str_n, MSGSIZE);
        }
        close(fd[1]);
        exit(0);
    }

    // Child process: fork == 0
    else{
        close(fd[1]);
        
        char read_n[MSGSIZE];
        while(read(fd[0], read_n, MSGSIZE)){
            printf("%s\n", read_n);
        }
        close(fd[0]);
        exit(0);
    }
}